dist: trusty
sudo: required
language: node_js
node_js:
  - "6"

services:
  - docker

#install:
#  - npm install

before_script:
#  - npm run pree2e
  - docker-compose run e2e npm install
  - docker-compose pull
  - docker-compose up -d selenium e2e stubby
  - sleep 60

script:
#  - ng lint
  - docker-compose run test
  - docker-compose run e2e npm run e2e-selenium

#after_success:
#  - npm run coveralls

before_deploy:
#  - npm run package

after_failure:
  - docker-compose logs
