version: '2'
services:
   e2e:
     image: node:6
     command: npm run start-ci
     volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
     working_dir: /usr/src/app
   selenium:
     image: selenium/standalone-chrome
     ports:
      - "4444:4444"
     links:
      - e2e
      - stubby
      - test
   stubby:
     image: node:6
     command: npm run stubby
     volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
     working_dir: /usr/src/app
   test:
     image: node:6
     command: npm run test-once
     volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
     working_dir: /usr/src/app
   test-chrome:
     image: markadams/chromium-xvfb-js
     command: npm run test-once -- -c karma-chrome.conf.js
     volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
     working_dir: /usr/src/app
volumes:
  node_modules: